main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('profile/', views.profile, name='profile'),
    path('experience/', views.experience, name='experience'),
    path('achievement/', views.achievement, name='achievement'),
    path('projects/', views.projects, name='projects'),
    path('story1/', views.story1, name='story1'),
    path('MatKul/', views.pelajaran, name='MatKul'),
    path('<int:pk>', views.mk_delete, name='Delete')

]

project_name/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/models.py
from django.db import models

# Create your models here.
class Matkul(models.Model):
    Name = models.TextField(max_length=50)
    NameDos = models.TextField(max_length=50)
    Sks = models.TextField(max_length=50)
    Desc = models.TextField(max_length=50)
    Year = models.TextField(max_length=50)
    Room = models.TextField(max_length=50)

main/forms.py
from django import forms
from .models import Matkul

class MatKulForm(forms.Form):
    Name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder' : 'Nama',
        'type' : 'text',
        'required' : True,
    }))

    NameDos = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder' : 'Nama Dosen',
        'type' : 'text',
        'required' : True,
    }))

    Sks = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder' : 'Jumlah SKS',
        'type' : 'text',
        'required' : True,
    }))

    Desc = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder' : 'Deskripsi',
        'type' : 'text',
        'required' : True,
    }))

    Year = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder' : 'Semester Tahun',
        'type' : 'text',
        'required' : True,
    }))

    Room = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder' : 'Kelas',
        'type' : 'text',
        'required' : True,
    }))

main/views.py
from django.shortcuts import render, redirect
from .models import Matkul as mk
from .forms import MatKulForm

def home(request):
    return render(request, 'main/home.html')

def profile(request):
    return render (request, 'main/profile.html')

def experience(request):
    return render (request, 'main/experience.html')

def achievement(request):
    return render (request, 'main/achievement.html')

def projects(request):
    return render (request, 'main/projects.html')

def story1(request):
    return render (request, 'main/story1.html')

def pelajaran(request):
    form = MatKulForm(request.POST)
    if request.method == "POST":
        if form.is_valid():
            stud = mk()
            stud.Name = form.cleaned_data['Name']
            stud.NameDos = form.cleaned_data['NameDos']
            stud.Sks = form.cleaned_data['Sks']
            stud.Desc = form.cleaned_data['Desc']
            stud.Year = form.cleaned_data['Year']
            stud.Room = form.cleaned_data['Room']
            stud.save()
            return redirect('main/matkul')
    stud = mk.objects.all()
    form = MatKulForm()
    response = {"stud":stud, 'form':form}
    return render(request,'main/matkul.html', response)

def mk_delete(request, pk):
    form = MatKulForm(request.POST)
    if request.method == "POST":
        if form.is_valid():
            stud = mk()
            stud.Name = form.cleaned_data['Name']
            stud.NameDos = form.cleaned_data['NameDos']
            stud.Sks = form.cleaned_data['Sks']
            stud.Desc = form.cleaned_data['Desc']
            stud.Year = form.cleaned_data['Year']
            stud.Room = form.cleaned_data['Room']
            stud.save()
        return redirect('main/matkul')
    else:
        mk.objects.filter(pk=pk).delete()
        data = mk.objects.all()
        form = MatKulForm()
        response = {"stud":data, 'form':form}
        return render(request,'main/matkul.html', response)

main/templates/main/MatKul.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<title>MatKul</title>
{% endblock head %}

{% block content %}
<form action='' method="POST">
    {% csrf_token %}
    {{ form }}
    <div class='center-items'>
        <input type="submit" class="btn btn-primary" value="Add Mata Kuliah">
    </div>
</form>

<table class="table">
    <thead>
        <tr>
            <th scope="col">Name</th>
            <th scope="col">Nama Dosen</th>
            <th scope="col">SKS</th>
            <th scope="col">Deskripsi</th>
            <th scope="col">Semester Tahun</th>
            <th scope="col">Kelas</th>
            <th scope="col">Delete</th>
        </tr>
    </thead>
    <tbody>
        {% for mk in stud %}
            <tr>
                <th scope="row">{{mk.Name}}</th>
                <td>{{mk.NameDos}}</td>
                <td>{{mk.Sks}}</td>
                <td>{{mk.Desc}}</td>
                <td>{{mk.Year}}</td>
                <td>{{mk.Room}}</td>
                <td><a href="{% url 'Delete' pk=mk.pk %}"><button class="btn btn-icon btn-danger">Delete</button></a></td>
                </tr>
            </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock content %}

main/templates/main/achievement.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<title>Achievement</title>
{% endblock head %}

{% block content %}
<div class="container-fluid">
    <div class="row">
          <div class="col">
            <h1>Coming Soon!
            </h1>
            <img src="{% static 'img/helloline.png' %}" alt="lines">
          </div>
    </div>
  </div>
{% endblock content %}

main/templates/main/experience.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<title>Experience</title>
{% endblock head %}

{% block content %}
<div class="container-fluid">
    <div class="row">
      <div class="col">
      <h1>Experience
      </h1>
      <img src="{% static 'img/helloline.png' %}" alt="lines">           
      <table class="table table-borderless">
        <tbody>
          <tr>
            <td><img src="{% static 'img/Rectangle 4.png' %}" alt="execom"></td>
            <td style="font-size: 20px;" class="badge">Execom 68
            <br>
            <br>
            <br>Wakil Ketua <br>Umum (2017-2018)
            </td>
          </tr>
          <tr>
            <td><img src="{% static 'img/Rectangle 5.png' %}" alt="execom"></td>
          <td style="font-size: 20px;" class="badge">Bazkom<br>Karasel
            <br>
            <br>
            <br>Penanggung Jawab 
            <br>Lomba FIFA 19 (2018)
          </td>
          </tr>
        </tbody>
      </table>
      </div>
    </div>
  </div>
{% endblock content %}

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<title>Home</title>
{% endblock head %}

{% block content %}
<div class="container-fluid">
  <div class="row">
        <div class="col">
          <h1>Hello!
          </h1>
          <img src="{% static 'img/helloline.png' %}" alt="lines">
          <p>
              Nama Saya Muhammad Farhan Ramadhan, biasa dipanggil Farhan. 
              Sekarang saya kuliah di Universitas Indonesia, Fakultas Ilmu Komputer, 
              jurusan Ilmu Komputer angkatan 2019. 
            <br>
            <span>MAUNG !</span> 
            <br>
              Selamat datang di web profil saya, dimana ada beberapa pengalaman, 
              prestasi, dan proyek(coming soon) yang saya pernah atau sedang lakukan.
            <br>
            <br>
            Terima kasih.
          </p> 
        </div>

        <div class="col">
            <img src="{% static 'img/mypic.png' %}" alt="MyProfilePic">
        </div>
  </div>
</div>
{% endblock content %}

main/templates/main/profile.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<title>Profile</title>
{% endblock head %}

{% block content %}
<div class="profile">
  <div class="container-fluid">
    <div class="row">
          <div class="col">
            <h1>Profile
            </h1>
            <img src="{% static 'img/helloline.png' %}" alt="lines">
            <dl>
                <dt>Nama</dt>
                <dd> -  Muhammad Farhan Ramadhan</dd>
                <dt>NPM</dt>
                <dd> -  1906306155</dd>
                <dt>Fakultas</dt>
                <dd> -   Fakultas Ilmu Komputer</dd>
                <dt>Angkatan</dt>
                <dd> -   2019</dd>
                <dt>Hobi</dt>
                <dd> -  Gaming, Futsal, Listening to music</dd>
                <dt>Riwayat Pendidikan</dt>
                <dd> -  SMAN 68 Jakarta (2016-2019)</dd>
                <dd> -  SMPN 216 Jakarta (2013-2016)</dd>
                <dd> -  SDN Johar Baru 01 Jakarta (2007-2013)</dd>
                <dt>Contacts</dt>
                <dd> - Whatsapp : +6285711112808</dd>
                <dd> - Line : muhfarhanram</dd>
                <dd> - Email : muhamad.farhan95@ui.ac.id</dd>
            </dl>
          </div>

    </div>
  </div>
</div>
{% endblock content %}

main/templates/main/projects.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<title>Projects</title>
{% endblock head %}

{% block content %}
<div class="container-fluid">
    <div class="row">
          <div class="col">
            <h1>Coming Soon!
            </h1>
            <img src="{% static 'img/helloline.png' %}" alt="lines">
          </div>
    </div>
  </div>
{% endblock content %}

main/templates/main/story1.html
<html>
<style>
    h1 {
        color: white;
        padding: 15px;
        font-size: 50px;
        font-family: Arial, Helvetica, sans-serif;
    }

    p {
        color: white;
        font-size: 18px;
        padding : 25px;
    }

    body {
        background-image: url('https://mcdn.wallpapersafari.com/medium/61/65/hkug7N.jpg');
        background-repeat: no-repeat;
        background-attachment: fixed;
        background-size : cover;
        font-family: Arial, Helvetica, sans-serif;
        padding: 30px;
    }

    table, th, td {
        background-color: rgb(122, 67, 250);
        border-bottom: 2px solid black;
        border-collapse: collapse;
        padding : 15px;
    }

    th, td {
        color :white;
    }

    table.center {
        margin-left: auto;
        margin-right: auto;
    }

    a:link {
        color:rgb(40, 233, 40)
    }

    a:hover {
        color: green;
    }

    a:visited {
        color: rgb(95, 16, 16);
    }

</style>
<h1>Hello World!</h1>
<p>Selamat datang di web profil saya, nama saya <b>Farhan</b>. Bisa dilihat dibawah ya profil saya!
    <br> Terima kasih.
</p>
<body>
    <table class="center">
        <tr>
            <td><b>Nama</b></td>
            <td>Muhammad Farhan Ramadhan</td>
        </tr>
        <tr>
            <td><b>About Me</b></td>
            <td>Gamer, Student, Future Programmer. Always think one step ahead everytime</td>
        </tr>
        <tr>
            <td><b>NPM</b></td>
            <td>1906306155</td>
        </tr>
        <tr>
            <td><b>Fakultas</b></td>
            <td>Faskultas Ilmu Komputer</td>
        </tr>
        <tr>
            <td><b>Angkatan</b></td>
            <td>2019</td>
        </tr>
        <tr>
            <td><b>Hobi</b></td>
            <td>Gaming, Futsal, Listening to music</td>
        </tr>
        <tr>
            <td><b>Riwayat Pendidikan</b></td>
            <td>SMAN 68 Jakarta (2016-2019)
                <br>SMPN 216 Jakarta (2013-2016)
                <br>SDN Johar Baru 01 Jakarta (2007-2013)
            </td>
        </tr>
        <tr>
            <td><b>Social Media</b></td>
            <td><a href="https://www.instagram.com/farhan_rmdhn17/" target="_blank`">Instagram</a>
                <br><a href="https://www.facebook.com/farhan.ramadhan.3192" target="_blank`">Facebook</a>
            </td>
        </tr>
        <tr>
            <td><b>Contacs</b></td>
            <td>Whatsapp : +6285711112808
                <br>Line : muhfarhanram
                <br>Email : muhamad.farhan95@ui.ac.id
            </td>
        </tr>
    </table>
</body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  <link href='https://fonts.googleapis.com/css?family=DM Sans' rel='stylesheet'>
  {% block head %}
  {% endblock head %} 
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-navbar">
    <a class="nav-link" href="{% url 'main:home' %}"><img class="home-btn" src="{% static 'img/home.svg' %}" alt=""></a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'main:profile' %}">Profile </a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'main:experience' %}">Experience</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'main:achievement' %}">Achievement</a>
        </li>
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'main:projects' %}">Projects</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'main:matkul' %}">Projects</a>
      </li>
      </ul> 
    </div>
  </nav>

  {% block content %}
  {% endblock content %}

  <div id="footer">
    <p>
      © Farhan Ramadhan
    </p>
    <div class="footer-logo">
    <ul>
        <li><a href="https://www.instagram.com/farhan_rmdhn17/"><img src="{% static 'img/instagram.svg' %}" alt="" class="logo"></a></li>
        <li><a href="https://www.facebook.com/farhan.ramadhan.3192"><img src="{% static 'img/facebook.svg' %}" alt="" class="logo"></a></li>
        <li><a href="{% url 'main:profile' %}"><img src="{% static 'img/whatsapp.svg' %}" alt="" class="logo"></a></li>
    </ul>
    </div>
  </div>
</body>
</html>